### ISSUE TITLE
카테고리 관리자 권한 crud 확인

### ISSUE THREAD

**Issue by kobumseouk** [kobumseouk/SpringBoots#13]
In GitLab by @GobumE on Oct 8, 2024, 10:20

- [x] 관리자 권한 설정(controller)
- [x] 관리자 권한 여부 확인 후 페이지 연결(js)   <- 로그인 필요
- [ ] 관리자 페이지 API 연결 
- [ ] 관리자 권한 crud 테스트

- [x] 공통 헤더 작업

**Comment by bumstone** [comment]
In GitLab by @GobumE on Oct 8, 2024, 10:54

marked the task **관리자 권한 설정(controller)** as completed

**Comment by bumstone** [comment]
In GitLab by @GobumE on Oct 8, 2024, 13:44

mentioned in commit 7705695fedb964369fbe50922a17690efaf22dae

**Comment by bumstone** [comment]
In GitLab by @GobumE on Oct 8, 2024, 13:44

mentioned in commit 8dadfaa5d1581b09d663b63ccfcf85af84346331

**Comment by bumstone** [comment]
In GitLab by @GobumE on Oct 8, 2024, 21:04

mentioned in commit d2a6d4b86cacea52a3eeb6e26e3c96ecd5ebb030

**Comment by bumstone** [comment]
In GitLab by @GobumE on Oct 8, 2024, 21:04

marked the task **관리자 권한 여부 확인 후 페이지 연결(js)   <- 로그인 필요** as completed

**Comment by bumstone** [comment]
In GitLab by @GobumE on Oct 9, 2024, 11:31

marked the task **관리자 페이지 API 연결** as completed

**Comment by bumstone** [comment]
In GitLab by @GobumE on Oct 9, 2024, 11:32

mentioned in commit 3603ecd07bd57ca63bbaafb6d024624bfb172556

**Comment by bumstone** [comment]
In GitLab by @GobumE on Oct 9, 2024, 15:10

mentioned in commit 3b0e970f502ffd990cf25d68ffbf93fec45d3ba8

**Comment by bumstone** [comment]
In GitLab by @GobumE on Oct 9, 2024, 15:15

mentioned in commit 1492c045640a136c54ec364680f602c52551be7d

**Comment by bumstone** [comment]
In GitLab by @GobumE on Oct 9, 2024, 15:41

mentioned in commit d4981f916f0c2160918cea1fef8e009934421373

**Comment by bumstone** [comment]
In GitLab by @GobumE on Oct 9, 2024, 15:42

mentioned in commit 44c54edfc692f65be381d55b268a16a4d53ad4f7

**Comment by bumstone** [comment]
In GitLab by @GobumE on Oct 9, 2024, 23:54

marked the task **관리자 페이지 API 연결** as incomplete

**Comment by bumstone** [comment]
In GitLab by @GobumE on Oct 9, 2024, 23:54

marked the task **공통 헤더 작업** as completed

**Comment by bumstone** [comment]
In GitLab by @GobumE on Oct 15, 2024, 04:57

mentioned in commit 700a22e3203476941591e7993e97fe36d3c6fa4b

**Comment by bumstone** [comment]
In GitLab by @leeseoyul on Oct 30, 2024, 20:42

mentioned in commit e5002ed5d93fe4c28d4e1f04828abe46f8f0f10b
