### ISSUE TITLE
상품 Front 작업

### ISSUE THREAD

**Issue by kobumseouk** [kobumseouk/SpringBoots#84]
In GitLab by @HyeonSeung on Oct 16, 2024, 16:20

- [x] : 상품 추가 페이지와 API 연결 작업
- [x] : 상품 추가 페이지 다중 SelectBox 수정
- [ ] : 상품 추가 페이지 디자인 변경 - 상품 추가 기능 UI 변경 - 기본적인 기능 구현 후 수정
- [x] : 상품 추가 후 CategoryDetail 페이지에 상품 요약 화면 출력히기 => 범석님이 만든 키워드 검색에서 나오는 상품 요약 부분 그대로 적용해보기 => 범석님이 제작
- [ ] : 상품 수정 페이지 만들기 - api 연결 필요
- [x] : 상품 리스트 페이지 만들기 - 페이지네이션 수정하기
- [x] : 상품 페이지 연결하기

**Comment by bumstone** [comment]
In GitLab by @HyeonSeung on Oct 18, 2024, 16:33

marked the task **: 상품 추가 HTML과 API 연결 작업** as completed

**Comment by bumstone** [comment]
In GitLab by @HyeonSeung on Oct 18, 2024, 16:33

marked the task **: 상품 추가 HTML 다중 SelectBox 수정** as completed

**Comment by bumstone** [comment]
In GitLab by @HyeonSeung on Oct 21, 2024, 00:11

marked the task **: 상품 페이지 연결하기** as completed

**Comment by bumstone** [comment]
In GitLab by @HyeonSeung on Oct 21, 2024, 13:45

marked the task **: 상품 리스트 페이지 만들기 - 페이지네이션 수정하기** as completed

**Comment by bumstone** [comment]
In GitLab by @HyeonSeung on Oct 21, 2024, 13:45

marked the task **: 상품 추가 후 CategoryDetail 페이지에 상품 요약 화면 출력히기 => 범석님이 만든 키워드 검색에서 나오는 상품 요약 부분 그대로 적용해보기 => 범석님이 제작** as completed
